/* tslint:disable */
/**
 * This file was automatically generated by Payload CMS.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    users: User;
    categories: Category;
    media: Media;
  };
}
export interface User {
  id: string;
  name?: string;
  roles?: ('admin' | 'user')[];
  email?: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  loginAttempts?: number;
  lockUntil?: string;
  createdAt: string;
  updatedAt: string;
  password?: string;
}
export interface Category {
  id: string;
  title?: string;
  parent?: string | Category;
  createdAt: string;
  updatedAt: string;
}
export interface Media {
  id: string;
  alt: string;
  featuredChar?: {
    [k: string]: unknown;
  }[];
  img: string;
  createdAt: string;
  updatedAt: string;
}
